# Generated by Django 5.1.6 on 2025-02-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
    ]
