# Generated by Django 5.1.6 on 2025-03-01 12:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20250223_1353'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('contenu', models.TextField(null=True)),
                ('url', models.CharField(max_length=255)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=500)),
                ('favoris', models.ManyToManyField(blank=True, related_name='favorite_actualites', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_actualites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
