# Generated by Django 5.1.6 on 2025-03-01 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_actualites'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualites',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='actualites', to='articles.categorie'),
        ),
    ]
